language: python
python:
  - 2.7
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - py.test
after_success:
  - pip install python-coveralls
  - coveralls
